### ISSUE TITLE
clone下来一直导入失败，我真的服。每次遇到这种导入依赖花大几个小时时间

### ISSUE THREAD

**Issue by zhsongdanc** [apache/dubbo-samples#1014]

**Comment by zhsongdanc** [comment]
还没具体看，白花了几个小时，真的生气

**Comment by AlbumenJ** [comment]
1. 功能多这个没办法，Dubbo 提供的能力实际上比 dubbo-samples 的还要多
2. 目前 samples 是支持某个子模块单独导入的，不需要从根目录导入
3. Maven 拉取慢的问题建议通过配置 Proxy 解决，网络问题我们无法解决

**Comment by tritone-l** [comment]
可以换成国内镜像源
