### ISSUE TITLE
类重复问题

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo-samples#102]
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>${dubbo.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
        </dependency>
上面是pom.xml的文件，然后运行就爆这样的错误
Duplicate class org/apache/dubbo/remoting/RemotingException.class in 2 jar
.m2/repository/org/apache/dubbo/dubbo/2.7.2/dubbo-2.7.2.jar!/org/apache/dubbo/remoting/RemotingException.class
.m2/repository/org/apache/dubbo/dubbo-remoting-api/2.7.2/dubbo-remoting-api-2.7.2.jar!/org/apache/dubbo/remoting/RemotingException.class]

**Comment by ralf0131** [comment]
Could you describe more clearly? It is hard to understand what you mean.

**Comment by jimiyi** [comment]
`<properties>
        <dubbo.version>2.7.2</dubbo.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>${dubbo.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-metadata-report-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>         
        </dependency>
    </dependencies>`
上面是我的pom.xml文件，貌似dubbo和dubbo-metadata-report-zookeeper 有重复的类
程序运行报错如下：
Duplicate class org/apache/dubbo/remoting/RemotingException.class in 2 jar .m2/repository/org/apache/dubbo/dubbo/2.7.2/dubbo-2.7.2.jar!/org/apache/dubbo/remoting/RemotingException.class .m2/repository/org/apache/dubbo/dubbo-remoting-api/2.7.2/dubbo-remoting-api-2.7.2.jar!/org/apache/dubbo/remoting/RemotingException.class]

**Comment by beiwei30** [comment]
cannot reproduce.
