### ISSUE TITLE
 How to cancel the parent node to write dependencies for the project dubbo-samples-native-image-registry-provider

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo-samples#1021]
project :
https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-native-image-registry/dubbo-samples-native-image-registry-provider/pom.xml
pom.xml:
![image](https://github.com/apache/dubbo-samples/assets/27885492/270787d0-ae34-4a2d-8d63-d604b8fceab1)

Can I not inherit this parent?If so,How to write pom.xml?

**Comment by AlbumenJ** [comment]
Yes, you can remove this. Dubbo add it for import some Apache default configs.
