### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by caiworld** [apache/dubbo-samples#112]
`<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>2.7.4-SNAPSHOT</version>
            <type>pom</type>
</dependency>`
why i can't find this dependence ? please answer , thanks

**Comment by Armstjoh** [comment]
me too

**Comment by htynkn** [comment]
It's snapshot version which available in apache snapshot repo.
Please use .mvn/settings.xml(https://github.com/apache/dubbo-samples/tree/master/.mvn) file or change to stable version
