### ISSUE TITLE
absence of dubbo-maven-address-plugin module for branch 2.6.x

### ISSUE THREAD

**Issue by wujun** [apache/dubbo-samples#117]
Because official maven repository doesn't support v 2.7.3 of dubbo now, I have to go back to branch v2.6.x. for integration test. But I can't found dubbo-maven-address-plugin module in repo and pom file

**Comment by htynkn** [comment]
2.7.3 is released. snapshot is available in apache snapshot repo.
Please use https://github.com/apache/dubbo-samples/blob/master/.mvn/settings.xml
