### ISSUE TITLE
consumer.xml for dubbo-samples-direct can't work.

### ISSUE THREAD

**Issue by maslke** [apache/dubbo-samples#118]
in this demo, there is "url" config in <dubbo:reference>.
something like <dubbo:reference id="directService" check="false" interface="org.apache.dubbo.samples.direct.api.DirectService"
                     url="${target.address:localhost}:20880" group="test" version="1.0.0-daily"/>

but it does not work. 
I have to add group and version part to url to make this demo work.

**Comment by biyuhao** [comment]
Hi, you can change `dubbo.version` to `2.7.4-SNAPSHOT` in `dubbo-samples-direct/pom.xml` as a workaround.
After dubbo-2.7.4 released we will update this pom file.
