### ISSUE TITLE
fail to "mvn clean install -Dmaven.test.skip=true" for java

### ISSUE THREAD

**Issue by iamorchid** [apache/dubbo-samples#131]
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.dubbo:dubbo-samples-grpc:1.0-SNAPSHOT (/home/will/workspace/dubbo-samples/java/dubbo-samples-grpc/pom.xml) has 1 error
[ERROR]     'packaging' with value 'jar' is invalid. Aggregator projects require 'pom' as packaging. @ line 20, column 109
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by htynkn** [comment]
Fixed. Please try with latest version
