### ISSUE TITLE
compiled

### ISSUE THREAD

**Issue by liushuiawen** [apache/dubbo-samples#161]
jdk1.8 ? I can't run DirectProvider in dubbo-samples-direct.

**Comment by htynkn** [comment]
yes it requires jdk8
could you provide morr information about your local error message

**Comment by liushuiawen** [comment]
启动DirectProvider main方法,
报 Error:(23, 43) java: 程序包org.springframework.context.support不存在
Error:(29, 9) java: 找不到符号
  符号:   类 ClassPathXmlApplicationContext
  位置: 类 org.apache.dubbo.samples.direct.DirectConsumer

但IDE编译没问题，jar也确实有引入

**Comment by htynkn** [comment]
reproduce same issue via https://www.katacoda.com/htynkn/scenarios/dubbo-samples-issue-161
compile pass and execute fail

**Comment by htynkn** [comment]
works in my local PC
<img width="1181" alt="屏幕快照 2020-05-05 下午3 49 42" src="https://user-images.githubusercontent.com/659135/81045077-12f7ad80-8ee8-11ea-9e16-c4ac69267b3f.png">
maven dependencies log all good:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.apache.dubbo:dubbo-samples-direct >----------------
[INFO] Building dubbo-samples-direct 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ dubbo-samples-direct ---
[INFO] org.apache.dubbo:dubbo-samples-direct:jar:1.0-SNAPSHOT
[INFO] +- org.apache.dubbo:dubbo:jar:2.7.5:compile
[INFO] |  +- org.springframework:spring-context:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.3.16.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.3.16.RELEASE:compile
[INFO] |  +- com.alibaba.spring:spring-context-support:jar:1.0.5:compile
[INFO] |  +- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO] |  +- io.netty:netty-all:jar:4.1.25.Final:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.20:compile
[INFO] +- org.apache.dubbo:dubbo-dependencies-zookeeper:pom:2.7.5:compile
[INFO] |  +- org.apache.curator:curator-recipes:jar:4.0.1:compile
[INFO] |  |  \- org.apache.curator:curator-framework:jar:4.0.1:compile
[INFO] |  |     \- org.apache.curator:curator-client:jar:4.0.1:compile
[INFO] |  |        \- com.google.guava:guava:jar:20.0:compile
[INFO] |  \- org.apache.zookeeper:zookeeper:jar:3.4.13:compile
[INFO] |     +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |     +- org.slf4j:slf4j-log4j12:jar:1.7.25:compile
[INFO] |     +- log4j:log4j:jar:1.2.17:compile
[INFO] |     +- jline:jline:jar:0.9.94:compile
[INFO] |     \- org.apache.yetus:audience-annotations:jar:0.5.0:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.springframework:spring-test:jar:4.3.16.RELEASE:test
[INFO]    \- org.springframework:spring-core:jar:4.3.16.RELEASE:compile
[INFO]       \- commons-logging:commons-logging:jar:1.2:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.104 s
[INFO] Finished at: 2020-05-05T15:46:21+08:00
[INFO] ------------------------------------------------------------------------
```

katacod:
<img width="1432" alt="屏幕快照 2020-05-05 下午3 59 43" src="https://user-images.githubusercontent.com/659135/81045782-78986980-8ee9-11ea-933f-fd09d3c763e2.png">


The way I try to reproduce is incorrect. the jar file is not a all-in-one jar, so it should use -classpath. I verify this samples in both my PC and katacoda. please check your IDE (maybe refresh project via maven import) or check katacode link to check again (https://www.katacoda.com/htynkn/scenarios/dubbo-samples-issue-161)

**Comment by liushuiawen** [comment]
mvn 的打包过程跟你的不一样，没有那些spring,dubbo包的打包
"C:\Program Files\Java\java-1.8.0-openjdk-1.8.0.242\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\common\dubbo-samples\java -Dmaven.home=E:\tools\apache-maven-3.6.32 -Dclassworlds.conf=E:\tools\apache-maven-3.6.32\bin\m2.conf "-Dmaven.ext.class.path=D:\Program Files\JetBrains\IntelliJ IDEA 2020.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2020.1\lib\idea_rt.jar=52333:D:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin" -Dfile.encoding=UTF-8 -classpath E:\tools\apache-maven-3.6.32\boot\plexus-classworlds-2.6.0.jar;E:\tools\apache-maven-3.6.32\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version2020.1 -s E:\tools\apache-maven-3.6.32\conf\settings.xml -DskipTests=true package
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.apache.dubbo:dubbo-samples-direct >----------------
[INFO] Building dubbo-samples-direct 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dubbo-samples-direct ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ dubbo-samples-direct ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dubbo-samples-direct ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory D:\common\dubbo-samples\java\dubbo-samples-direct\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ dubbo-samples-direct ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ dubbo-samples-direct ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ dubbo-samples-direct ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.703 s
[INFO] Finished at: 2020-05-05T18:39:06+08:00
[INFO] ------------------------------------------------------------------------

**Comment by htynkn** [comment]
是的，maven打出来的jar默认没有依赖，如果你需要带依赖的all in one的包可以用maven对应插件打

**Comment by liushuiawen** [comment]
![IMG20200505-223156](https://user-images.githubusercontent.com/11494415/81078042-4a824c00-8f20-11ea-9ec6-37b49554872d.jpeg)

**Comment by liushuiawen** [comment]
it's so strange.
