### ISSUE TITLE
HelloWorld 跑不通

### ISSUE THREAD

**Issue by SocketNet** [apache/dubbo-samples#171]
server
> ![image](https://user-images.githubusercontent.com/10844093/90090274-2f607d00-dd56-11ea-8b50-2e84cbfdb32b.png)
client
> ![image](https://user-images.githubusercontent.com/10844093/90090294-3a1b1200-dd56-11ea-94c0-b19c9362f10e.png)

**Comment by AlexStocks** [comment]
Pls read dubbo-go & dubbo-samples readme carefully.
