### ISSUE TITLE
能否增加对接Prometheus的例子，或者使用metrics的事例（go语言）

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-samples#174]
能否增加对接Prometheus的例子，或者使用metrics的事例（go语言）？
谢谢

**Comment by AlexStocks** [comment]
cc @fangyincheng @zouyx  pls answer this question.

**Comment by zouyx** [comment]
@whitekeyboard I think it is ok, i will provide it in this week , what do you think?

**Comment by whitekeyboard** [comment]
好的，多谢，如果可以的话，希望还可以增加熔断和降级的例子，这个在实际应用中也比较常见，尝试写了几个例子，感觉都不是特别好！

**Comment by zouyx** [comment]
> 好的，多谢，如果可以的话，希望还可以增加熔断和降级的例子，这个在实际应用中也比较常见，尝试写了几个例子，感觉都不是特别好！

我今天看了下，Prometheus 并不易用，我可能会改下。如果你急着用，我可以给你现在使用的方式。

**Comment by zouyx** [comment]
Prometheus  samples : https://github.com/dubbogo/dubbo-samples/tree/master/golang/metric/dubbo

Prometheus can connect to dubbo-go collect metric data.

![截屏2020-08-25下午11 18 36](https://user-images.githubusercontent.com/3828072/91193542-c8fe3600-e729-11ea-9846-42b639943376.png)

**Comment by zouyx** [comment]
any problem now?

**Comment by whitekeyboard** [comment]
no ,thanks!
