### ISSUE TITLE
kubernetes是否可以基于最新的DUBBO版本提供镜像

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-samples#182]
https://github.com/apache/dubbo-samples/tree/master/golang/registry/kubernetes
此例子是基于dubbo-v1.3.0的版本，且为2020年3月16日的版本，当前dubbogo中已经提交了很次代码，建议基于最新dubbo-go提供一个新的镜像范例。当前的例子应该不兼容最新的dubbo-go了，比如DUBBO_NAMESPACE环境变量的注入。

谢谢！

**Comment by AlexStocks** [comment]
@whitekeyboard would u pls move this issue to github.com/apache/dubbo-go-samples?

**Comment by whitekeyboard** [comment]
已经在github.com/apache/dubbo-go-samples重新了一个新的issue

**Comment by AlexStocks** [comment]
> 已经在github.com/apache/dubbo-go-samples重新了一个新的issue

got it. thx.
