### ISSUE TITLE
Can't find dubbo-compiler:pom:0.0.4-SNAPSHOT

### ISSUE THREAD

**Issue by MingJunDuan** [apache/dubbo-samples#397]
Master branch, can't find dubbo-compiler:pom:0.0.4-SNAPSHOT when compiling source code in Dubbo-samples-triple module

**Comment by yl-yue** [comment]
解决方案1：把整个工程拉下来，会自动依赖他们的快照库
解决方案2：切换0.0.3版本
解决方案3：催促官方发布0.0.4

**Comment by EarthChen** [comment]
现在compile 代码和版本均已和主仓库同步，直接使用dubbo 的 version 即可
