### ISSUE TITLE
代码不规范，各模块中有大量的重复代码。在ide中显示白色重复，难以阅读。

### ISSUE THREAD

**Issue by x-seeing** [apache/dubbo-samples#44]
代码不规范，各模块中有大量的重复代码。在ide中显示白色重复，难以阅读。
例如：org.apache.dubbo.samples.basic.EmbeddedZooKeeper.ServerRunnable#run
org.apache.dubbo.samples.validation.EmbeddedZooKeeper.ServerRunnable#run

**Comment by ralf0131** [comment]
Hi, thanks for reporting, would you like to fix it by sending a pull request?

**Comment by wuhulala** [comment]
抽取一个工程放置这些工具？可否？如果可以后面会删除修改相关的代码，改为引用PR(https://github.com/apache/incubator-dubbo-samples/pull/51)

**Comment by beiwei30** [comment]
we intend to make samples independent to each other, pls. check if the problem still exists in the latest samples
