### ISSUE TITLE
引入spring-cloud-starter-netflix-hystrix包无效，相关注解编译不过

### ISSUE THREAD

**Issue by grindwheel** [apache/dubbo-samples#5]
请问，@EnableHystrix，@HystrixCommand 等注解无法识别是什么原因，pom已引入了<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
            <version>1.4.4.RELEASE</version>
        </dependency>

**Comment by hengyunabc** [comment]
demo的代码应该是没有问题的。把Demo导入ide里跑下

**Comment by grindwheel** [comment]
![img20180628_194814](https://user-images.githubusercontent.com/10232714/42032486-4962f3ee-7b0c-11e8-9104-078957d9e3cc.png)

**Comment by grindwheel** [comment]
就是demo导入进去的代码，无法识别这些注解

**Comment by hengyunabc** [comment]
检查本地的maven仓库，试下清理掉 spring boot相关的目录，重新编绎

**Comment by grindwheel** [comment]
但运行的时候报这个错：
![image](https://user-images.githubusercontent.com/10232714/42279237-bde72b0a-7fcf-11e8-9bf8-923fe6f0cd93.png)

**Comment by grindwheel** [comment]
上面的问题是我将包升级到2.0.0时报的错误
![image](https://user-images.githubusercontent.com/10232714/42297967-c2b2cf98-8035-11e8-949d-c7c675cb42d9.png)

但是如果不升级包的话，注解就无法识别，编译报错

**Comment by diecui1202** [comment]
@grindwheel Have you solved this problem ?

**Comment by zhaoweihua32** [comment]
interesting

**Comment by Zhangxuesongd** [comment]
i have this problem too

**Comment by rogenLee** [comment]
problem too,trying

**Comment by beiwei30** [comment]
pls. try again.

**Comment by zhanghuanpro** [comment]
me too
