### ISSUE TITLE
dubbo-samples-kubernetes  （使用k8s做注册中心），消费端报No provider available

### ISSUE THREAD

**Issue by szhengli** [apache/dubbo-samples#501]
我只改dubbo.registry.address kubernetes api server 地址。和镜像地址。  代码部分没有改的,包括dubbo版本（3.1.0.SNAPSHOT）也没改。

部署到k8s后，provider 可以正常启动并注册到k8s service。 但consumer 报 

main ERROR config.ReferenceConfig: [DUBBO] No provider available., dubbo version: 3.1.0, current host: 10.42.2.83, error code: 2-2. This may be caused by server crashed, go to https://dubbo.apache.org/faq/2/2 to find instructions.
--
java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.api.GreetingService. No provider available for the service org.apache.dubbo.samples.api.GreetingService from the url consumer://10.42.2.83/org.apache.dubbo.samples.api.GreetingService?application=dubbo-samples-apiserver-consumer&background=false&dubbo=2.0.2&interface=org.apache.dubbo.samples.api.GreetingService&metadata-service-port=20885&methods=sayHello&pid=1&provided-by=dubbo-samples-apiserver-provider&qos.accept.foreign.ip=true&qos.enable=true&register.ip=10.42.2.83&release=3.1.0&side=consumer&sticky=false&timeout=3000&timestamp=1661506877834 to the consumer 10.42.2.83 use dubbo version 3.1.0
at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:652)

有人成功部署过个这个sample代码到k8s中吗？  我们交流下（opre@163.com）
麻烦哪位大佬帮忙看下。谢谢

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo-samples/pull/504
