### ISSUE TITLE
dubbo-samples-annotation 示例 POM 未指定版本号

### ISSUE THREAD

**Issue by JerryChin** [apache/dubbo-samples#62]
https://github.com/apache/incubator-dubbo-samples/blob/2e9b0799d15c837d4ad3163286d92729d18adde6/dubbo-samples-annotation/pom.xml#L37-L41

依赖 `dubbo-metadata-report-api` 版本号未指定，请指定一下。

**Comment by beiwei30** [comment]
no longer valid, pls. check the latest code.
