### ISSUE TITLE
dubbo-samples-async-simple模块的AsyncConsumer运行出现NPE

### ISSUE THREAD

**Issue by lizanle521** [apache/dubbo-samples#64]
incubator-dubbo-samples/dubbo-samples-async/dubbo-samples-async-simple/src/main/java/org/apache/dubbo/samples/governance/AsyncConsumer.java，
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.samples.governance.AsyncConsumer.main(AsyncConsumer.java:42)

**Comment by lizanle521** [comment]
<dubbo:reference id="asyncService" async="true" interface="org.apache.dubbo.samples.governance.api.AsyncService"/> 添加属性为async="true"可以解决

**Comment by beiwei30** [comment]
cannot reproduce, pls. try again with 2.7.4-SNAPSHOT.
