### ISSUE TITLE
docker启动dubbo项目之后，telnet可以通信，注册中心的IP还是容器IP

### ISSUE THREAD

**Issue by wjyuian** [apache/dubbo-samples#71]
最近遇到docker容器中运行dubbo provider时，注册ip的问题。

找到样例[](https://github.com/apache/incubator-dubbo-samples/tree/master/dubbo-samples-docker)https://github.com/apache/incubator-dubbo-samples/tree/master/dubbo-samples-docker；

按照里面的示例，成功运行容器，并且指定的IP，telnet可以正常操作，应该是可以通信的。

不过，注册到注册中心的还是容器的IP，意味着消费者获取的IP还是无法通信的。

是不是要升级到最新的dubbo？

**Comment by Feeeenng** [comment]
mark

**Comment by Feeeenng** [comment]
我已经解决了  我是用docker-compose运行的
只要增加参数
```yaml
hostname: localhost  # 设置你的主机名 dubbo注册的IP就是宿主机的IP了  官网上的这些都没用！实测
```

**Comment by liu2510865** [comment]
![image](https://user-images.githubusercontent.com/4935445/60336765-d14acc00-99d3-11e9-8aaf-c3cf823ae717.png)
 docker run --name alfred_mobile_service -e DUBBO_IP_TO_REGISTRY=10.0.21.91 -e DUBBO_PORT_TO_REGISTRY=20890 -p 10.0.21.91:20890:20890   -it --rm -d liu2510865/alfred_mobile_service

老哥 我这样启也是无效   命令启咋起呢？

**Comment by Feeeenng** [comment]
根据你的命令只要改成
```
docker run --hostname 主机名  --name alfred_mobile_service -v /etc/hosts:/etc/hosts -p 10.0.21.91:20890:20890 -it --rm -d liu2510865/alfred_mobile_service
```
主机名对应ip 写在hosts里面 并且映射到容器ip 挂在hosts就可以啦

**Comment by liu2510865** [comment]
> 根据你的命令只要改成
> 
> ```
> docker run --hostname 主机名  --name alfred_mobile_service -v /etc/hosts:/etc/hosts -p 10.0.21.91:20890:20890 -it --rm -d liu2510865/alfred_mobile_service
> ```
> 
> 主机名对应ip 写在hosts里面 并且映射到容器ip 挂在hosts就可以啦

多谢  已经搞定了

**Comment by beiwei30** [comment]
`-e DUBBO_IP_TO_REGISTRY=` 应该是工作的。samples 里大部分例子都是基于这个在做： https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-docker/pom.xml#L126

**Comment by liu2510865** [comment]
> DUBBO_IP_TO_REGISTRY

DUBBO_IP_TO_REGISTRY 这个环境变量的读法 对dubbo的版本有要求的

**Comment by tfssweb** [comment]
> 我已经解决了 我是用docker-compose运行的
> 只要增加参数
> 
> ```yaml
> hostname: localhost  # 设置你的主机名 dubbo注册的IP就是宿主机的IP了  官网上的这些都没用！实测
> ```
我的一直没有生效

**Comment by redwolf2019** [comment]
Dubbo2.7.3+Nacos1.1.4/Nacos1.1.3一样的问题,容器里可以获取到DUBBO_IP_TO_REGISTRY的变量,但是dubbo里获取的还是容器的IP
