### ISSUE TITLE
add scenario in the dubbo-samples-metrics-prometheus

### ISSUE THREAD

**Issue by dengWuuu** [apache/dubbo-samples#778]
now there are only one scenario in this sample and i will add more scenario

**Comment by dengWuuu** [comment]
https://github.com/apache/dubbo-samples/pull/776 
this is the pr

**Comment by songxiaosheng** [comment]
测试场景：
Scenarios requiring multiple providers and consumers in a single demo application

需要单个demo应用中既有多个提供者又有多个消费者的场景

**Comment by dengWuuu** [comment]
> 测试场景： Scenarios requiring multiple providers and consumers in a single demo application
> 
> 需要单个demo应用中既有多个提供者又有多个消费者的场景

done
