### ISSUE TITLE
Not Springboot3.0?

### ISSUE THREAD

**Issue by EddyChina** [apache/dubbo-samples#789]
我看依赖时springboot2.7啊？ https://www.infoq.cn/article/lavbfbitzexeqq2czasi 这里说是springboot3.0的demo。。

**Comment by AlbumenJ** [comment]
可以参考下这个哈 https://github.com/apache/dubbo-samples/tree/master/10-task/dubbo-samples-rpc-basic

**Comment by EddyChina** [comment]
感谢> 可以参考下这个哈 https://github.com/apache/dubbo-samples/tree/master/10-task/dubbo-samples-rpc-basic
