### ISSUE TITLE
如果需要在springboot-actuator中返回dubbo的指标信息,dubbo 版本必须为3.2.0-beta.6 以上

### ISSUE THREAD

**Issue by EddyChina** [apache/dubbo-samples#791]
`如果需要在springboot-actuator中返回dubbo的指标信息,dubbo 版本必须为3.2.0-beta.6 以上`

但实际上并没有3.2.0-beta.6的依赖。

metrics的示例代码里有用到3.2.0-beta.6.SNAPSHOT 但中央仓库也没有，如何解决？

**Comment by AlbumenJ** [comment]
`3.2.0-beta.6` 在今天早上已经推送

**Comment by AlbumenJ** [comment]
https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/

**Comment by EddyChina** [comment]
会推送到repo.maven.org吗？

**Comment by EddyChina** [comment]
> https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/

会推送到repo.maven.org吗？

**Comment by AlbumenJ** [comment]
@songxiaosheng PTAL

**Comment by songxiaosheng** [comment]
> > https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/
> 我替换了beta6，但是ip:port/metrics 返回的内容里并没有dubbo_provider相关的指标信息，在nacos控制台是能查到providers:服务列表的。 这是什么原因呢？ 是上报的指标不全么？ 有没有相关日志或者代码点位可以debug的？
> 感谢。

消费者与提供者指标存在覆盖的问题，问题已经修复，最新代码在3.2分支，需要自行打包本地测试

**Comment by songxiaosheng** [comment]
> > https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/
> 我替换了beta6，但是ip:port/metrics 返回的内容里并没有dubbo_provider相关的指标信息，在nacos控制台是能查到providers:服务列表的。 这是什么原因呢？ 是上报的指标不全么？ 有没有相关日志或者代码点位可以debug的？
> 感谢。

有发起RPC调用么，MetricsFilter过滤器中对请求进行了采样

**Comment by EddyChina** [comment]
> > > https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/
> > > 我替换了beta6，但是ip:port/metrics 返回的内容里并没有dubbo_provider相关的指标信息，在nacos控制台是能查到providers:服务列表的。 这是什么原因呢？ 是上报的指标不全么？ 有没有相关日志或者代码点位可以debug的？
> > > 感谢。
> 
> 有发起RPC调用么，MetricsFilter过滤器中对请求进行了采样

哦哦。没有发起RPC。 我去RPC，有结果了回来更新。

**Comment by EddyChina** [comment]
> > > https://repo1.maven.org/maven2/org/apache/dubbo/dubbo/3.2.0-beta.6/
> > > 我替换了beta6，但是ip:port/metrics 返回的内容里并没有dubbo_provider相关的指标信息，在nacos控制台是能查到providers:服务列表的。 这是什么原因呢？ 是上报的指标不全么？ 有没有相关日志或者代码点位可以debug的？
> > > 感谢。
> 
> 有发起RPC调用么，MetricsFilter过滤器中对请求进行了采样

OK了。 发起后有provider的相关指标了。🙏
