### ISSUE TITLE
缺少DemoService、HelloReply、HelloRequest 类

### ISSUE THREAD

**Issue by stoneJava** [apache/dubbo-samples#986]
![image](https://github.com/apache/dubbo-samples/assets/17800109/00ed02d1-0b22-4eba-8fc7-96105b185a6c)
如图，缺少这几个类

**Comment by AlbumenJ** [comment]
这个是 protobuf 动态编译的，可以通过 mvn compile 生成

**Comment by stoneJava** [comment]
懂了，谢谢
