### ISSUE TITLE
按照subbo-sample-api中readme上面的步骤无法获得想要结果

### ISSUE THREAD

**Issue by lsongseven** [apache/dubbo-samples#99]
总是提示
`java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.samples.api.GreetingsService. No provider available for the service org.apache.dubbo.samples.api.GreetingsService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=first-dubbo-consumer&dubbo=2.0.2&interface=org.apache.dubbo.samples.api.GreetingsService&lazy=false&methods=sayHi&pid=3548&register.ip=x.x.x.x&release=2.7.2&side=consumer&sticky=false&timestamp=1561425149873 to the consumer x.x.x.x use dubbo version 2.7.2`
其中x.x.x.x是本机ip，求问什么原因。。

**Comment by lnwbzmt** [comment]
一样的问题，求解答

**Comment by beiwei30** [comment]
if you are using `multicast://` as the registry protocol, you need to specify `-Djava.net.preferIPv4Stack=true` before start your application.
